using Postgrest.Attributes;
using Postgrest.Models;

namespace MaterialeShop.Admin.Src.Dtos;

public class BaseModelApp : BaseModel
{
    [PrimaryKey("Id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("CreatedAt")]
    public DateTime? CreatedAt { get; set; } = new DateTime();
}