using System;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace MaterialeShop.Admin.Src.Dtos;

[Table("Lista")]
public class Lista : BaseModelApp
{
    [PrimaryKey("Id", false)] // Key is Autogenerated
    public int Id { get; set; }
    
    [Column("CreatedAt")]
    public DateTime? CreatedAt { get; set; } = new DateTime();

    [Column("PerfilId")]
    public int PerfilId { get; set; }

    [Column("Endereco")]
    public string? Endereco { get; set; }

    [Column("Status")]
    public string? Status { get; set; }

}
