using System;
using System.ComponentModel.DataAnnotations;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace MaterialeShop.Admin.Src.Dtos;

[Table("Loja")]
public class Loja : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public int Id { get; set; }
    
    [Column("created_at")]
    public string? CreatedAt { get; set; }

    [Required]
    [Column("nome")]
    public string Nome { get; set; }

    [Column("cnpj")]
    public string? Cnpj { get; set; }
    
    [Column("email")]
    public string? Email { get; set; }
    
    [Column("telefone")]
    public string? Telefone { get; set; }
    
    [Column("endereco")]
    public string? Endereco { get; set; }
    
    [Column("cidade")]
    public string? Cidade { get; set; }
    
    [Column("estado")]
    public string? Estado { get; set; }

}
