using System;
using System.ComponentModel.DataAnnotations;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace MaterialeShop.Admin.Src.Dtos;

[Table("UsuarioPerfil")]
public class UsuarioPerfil : BaseModel
{
    [PrimaryKey("Id", false)] // Key is Autogenerated
    public int Id { get; set; }

    [Column("Uuid")]
    public string? Uuid { get; set; }

    [Column("CreatedAt")]
    public string? CreatedAt { get; set; }

    [Column("Email")]
    [EmailAddress]
    public string? Email { get; set; }

    [Required]
    [Column("NomeCompleto")]
    public string NomeCompleto { get; set; }

    [Column("Cpf")]
    public string? Cpf { get; set; }

    [Column("Telefone")]
    public string? Telefone { get; set; }

    // Note: this is important so the MudSelect can compare pizzas
    public override bool Equals(object o)
    {
        var other = o as UsuarioPerfil;
        return other?.Id == Id;
    }

    // Note: this is important too!
    public override int GetHashCode() => NomeCompleto?.GetHashCode() ?? 0;

    // Implement this for the Pizza to display correctly in MudSelect
    public override string ToString() => NomeCompleto;

}
