using System;
using Postgrest.Attributes;
using Postgrest.Models;
using Supabase;

namespace MaterialeShop.Admin.Src.Dtos;

[Table("UsuarioPerfil")]
public class UsuarioPerfil : BaseModel
{
    [PrimaryKey("id", false)] // Key is Autogenerated
    public string Id { get; set; }

    [Column("email")]
    public string? Email { get; set; }
    
    [Column("nomecompleto")]
    public string? NomeCompleto { get; set; }

}
